project_id = "ajwolqgoqlrqyrlaiaix"

[functions.create-payment]
verify_jwt = false

[functions.check-payment]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.nexano-webhook]
verify_jwt = false
